### PR TITLE
added the rest of the files

### PR DESCRIPTION
**Pull request by AlejandroVI99**
# Description
What did you implemented/Why did you implemented this:
- we added the rest of the files, like the gemfile
- we erase some unnecessary comments
- we added some routes
- we added some CR of the last pull request

### CODE REVIEW

**Review by SampabloC — APPROVED** [review]
LGTM 🤟

**Comment by SaraNavarro** [comment]
Nice!

**Review by xFerchoVJ — APPROVED** [review]
LGTM!

**Review by OmarRoBra — COMMENTED** [review]
Good Job :)

**Comment by RobertoCarMed** [comment]
LGTM!

**Pull request merged**
